export const LAUNCH_CREATE_PROJECT = "LAUNCH_CREATE_PROJECT"
export const LAUNCH_PROJECT_VIEW = "LAUNCH_PROJECT_VIEW"
export const LAUNCH_TASK_VIEW = "LAUNCH_TASK_VIEW"
export const LAUNCH_CREATE_TASK = "LAUNCH_CREATE_TASK"
